// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3xc0_3VpDv3Ynjs1JuUKI3glxq4jPyfA',
    appId: '1:305938177329:web:3e386b35c80a48d05f6410',
    messagingSenderId: '305938177329',
    projectId: 'lona---dashboard',
    authDomain: 'lona---dashboard.firebaseapp.com',
    storageBucket: 'lona---dashboard.firebasestorage.app',
    measurementId: 'G-1J8T23PQVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJvXgk6vdZJLdODPb9KcFKCMfT6XaXQeg',
    appId: '1:305938177329:android:368e78f140999aba5f6410',
    messagingSenderId: '305938177329',
    projectId: 'lona---dashboard',
    storageBucket: 'lona---dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIIAu3MUUmYB1OgOlIf_LEmSOE6wBtRdY',
    appId: '1:305938177329:ios:31b741648051ed4f5f6410',
    messagingSenderId: '305938177329',
    projectId: 'lona---dashboard',
    storageBucket: 'lona---dashboard.firebasestorage.app',
    iosBundleId: 'com.example.webDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIIAu3MUUmYB1OgOlIf_LEmSOE6wBtRdY',
    appId: '1:305938177329:ios:31b741648051ed4f5f6410',
    messagingSenderId: '305938177329',
    projectId: 'lona---dashboard',
    storageBucket: 'lona---dashboard.firebasestorage.app',
    iosBundleId: 'com.example.webDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3xc0_3VpDv3Ynjs1JuUKI3glxq4jPyfA',
    appId: '1:305938177329:web:ca7ee8eef9d434d95f6410',
    messagingSenderId: '305938177329',
    projectId: 'lona---dashboard',
    authDomain: 'lona---dashboard.firebaseapp.com',
    storageBucket: 'lona---dashboard.firebasestorage.app',
    measurementId: 'G-2TNJ3R6RRC',
  );
}
